// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeeklyUp.Infrastructure.Persistence;

#nullable disable

namespace WeeklyUp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260227111837_AddStripeCustomerIdToUser")]
    partial class AddStripeCustomerIdToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeeklyUp.Domain.Entities.Integration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<string>("PropertyId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("property_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_account_id");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ix_integrations_user_provider")
                        .HasFilter("status != 'Disconnected'");

                    b.ToTable("integrations", "public");
                });

            modelBuilder.Entity("WeeklyUp.Domain.Entities.ManualMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("NewCustomers")
                        .HasColumnType("integer")
                        .HasColumnName("new_customers");

                    b.Property<decimal?>("Revenue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("revenue");

                    b.Property<int?>("SalesCount")
                        .HasColumnType("integer")
                        .HasColumnName("sales_count");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("Visits")
                        .HasColumnType("integer")
                        .HasColumnName("visits");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "WeekStart")
                        .IsUnique()
                        .HasDatabaseName("ix_manual_metrics_user_week");

                    b.ToTable("manual_metrics", "public");
                });

            modelBuilder.Entity("WeeklyUp.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Demographics")
                        .HasColumnType("jsonb")
                        .HasColumnName("demographics");

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_sent_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("WhatsAppSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("whatsapp_sent_at");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reports_user_created");

                    b.ToTable("reports", "public");
                });

            modelBuilder.Entity("WeeklyUp.Domain.Entities.ReportPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("SendDay")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("send_day");

                    b.Property<TimeOnly>("SendTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("send_time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.PrimitiveCollection<List<string>>("_enabledSections")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("enabled_sections");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_report_preferences_user");

                    b.ToTable("report_preferences", "public");
                });

            modelBuilder.Entity("WeeklyUp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("business_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalAuthId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_auth_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Free")
                        .HasColumnName("plan");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("verification_token");

                    b.HasKey("Id");

                    b.HasIndex("ExternalAuthId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_external_auth_id")
                        .HasFilter("external_auth_id IS NOT NULL");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("WeeklyUp.Domain.Entities.Integration", b =>
                {
                    b.HasOne("WeeklyUp.Domain.Entities.User", null)
                        .WithMany("Integrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_integrations_users");
                });

            modelBuilder.Entity("WeeklyUp.Domain.Entities.Report", b =>
                {
                    b.OwnsOne("WeeklyUp.Domain.ValueObjects.DateRange", "WeekRange", b1 =>
                        {
                            b1.Property<Guid>("ReportId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("End")
                                .HasColumnType("date")
                                .HasColumnName("week_end");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("date")
                                .HasColumnName("week_start");

                            b1.HasKey("ReportId");

                            b1.ToTable("reports", "public");

                            b1.WithOwner()
                                .HasForeignKey("ReportId");
                        });

                    b.OwnsOne("WeeklyUp.Domain.ValueObjects.ReportInsights", "Insights", b1 =>
                        {
                            b1.Property<Guid>("ReportId");

                            b1.Property<string>("Alert")
                                .IsRequired();

                            b1.Property<DateTime>("GeneratedAt");

                            b1.Property<string>("Highlight")
                                .IsRequired();

                            b1.Property<string>("Tip")
                                .IsRequired();

                            b1.HasKey("ReportId");

                            b1.ToTable("reports", "public");

                            b1.ToJson("insights");

                            b1.WithOwner()
                                .HasForeignKey("ReportId");
                        });

                    b.OwnsOne("WeeklyUp.Domain.ValueObjects.ReportMetrics", "Metrics", b1 =>
                        {
                            b1.Property<Guid>("ReportId");

                            b1.Property<int>("NewCustomers");

                            b1.Property<int>("PageViews");

                            b1.Property<int?>("PreviousVisits");

                            b1.Property<int>("SalesCount");

                            b1.Property<string>("TopPage");

                            b1.Property<string>("TopTrafficSource");

                            b1.Property<int>("TotalVisits");

                            b1.Property<int>("UniqueVisitors");

                            b1.HasKey("ReportId");

                            b1.ToTable("reports", "public");

                            b1.ToJson("metrics");

                            b1.WithOwner()
                                .HasForeignKey("ReportId");

                            b1.OwnsOne("WeeklyUp.Domain.ValueObjects.Money", "AverageTicket", b2 =>
                                {
                                    b2.Property<Guid>("ReportMetricsReportId");

                                    b2.Property<decimal>("Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired();

                                    b2.HasKey("ReportMetricsReportId");

                                    b2.ToTable("reports", "public");

                                    b2.WithOwner()
                                        .HasForeignKey("ReportMetricsReportId");
                                });

                            b1.OwnsOne("WeeklyUp.Domain.ValueObjects.Money", "PreviousRevenue", b2 =>
                                {
                                    b2.Property<Guid>("ReportMetricsReportId");

                                    b2.Property<decimal>("Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired();

                                    b2.HasKey("ReportMetricsReportId");

                                    b2.ToTable("reports", "public");

                                    b2.WithOwner()
                                        .HasForeignKey("ReportMetricsReportId");
                                });

                            b1.OwnsOne("WeeklyUp.Domain.ValueObjects.Money", "Revenue", b2 =>
                                {
                                    b2.Property<Guid>("ReportMetricsReportId");

                                    b2.Property<decimal>("Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired();

                                    b2.HasKey("ReportMetricsReportId");

                                    b2.ToTable("reports", "public");

                                    b2.WithOwner()
                                        .HasForeignKey("ReportMetricsReportId");
                                });

                            b1.Navigation("AverageTicket")
                                .IsRequired();

                            b1.Navigation("PreviousRevenue");

                            b1.Navigation("Revenue")
                                .IsRequired();
                        });

                    b.Navigation("Insights");

                    b.Navigation("Metrics");

                    b.Navigation("WeekRange")
                        .IsRequired();
                });

            modelBuilder.Entity("WeeklyUp.Domain.Entities.User", b =>
                {
                    b.OwnsOne("WeeklyUp.Domain.ValueObjects.BusinessName", "BusinessName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("business_name");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "public");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("WeeklyUp.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_users_email");

                            b1.ToTable("users", "public");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("BusinessName")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("WeeklyUp.Domain.Entities.User", b =>
                {
                    b.Navigation("Integrations");
                });
#pragma warning restore 612, 618
        }
    }
}
